### ISSUE TITLE
BomParserFactory does not close file

### ISSUE THREAD

**Issue by robertklaus-bosch** [CycloneDX/cyclonedx-core-java#103]
In ```BomParserFactory``` there is following line ~37:
``` final byte[] bytes = IOUtils.toByteArray(new FileInputStream(file), 1);```

The FileInputStream is not closed, thus the file handle stays open. Maybe enclosing it in a try-resource would be better.

**Comment by stevespringett** [comment]
Good catch

**Comment by stevespringett** [comment]
This fix will be available in v5.0 - which is currently a work in progress.
