### ISSUE TITLE
create sbom from zip file

### ISSUE THREAD

**Issue by VASAVI512** [CycloneDX/cyclonedx-core-java#122]
Hello,

What are the steps to create Java SBOM ? . I have a java based zip folder to create SBOM out of it. 
Can you share the steps to create SBOM

Regards,
Vasavi

**Comment by stevespringett** [comment]
There are Maven and Gradle plugins for Java. If you have a bunch of unmanged jars on the filesystem, you may want to investigate binary analysis tools. Questions like this should be directed to the projects Slack workspace.
