### ISSUE TITLE
Question or issue related to Dependency class

### ISSUE THREAD

**Issue by goneall** [CycloneDX/cyclonedx-core-java#168]
The [Dependency](https://github.com/CycloneDX/cyclonedx-core-java/blob/8d402ead325a6964eb3590217de043363ce237d2/src/main/java/org/cyclonedx/model/Dependency.java#L43) class does not seem to match the [JSON documentation on dependencies](https://cyclonedx.org/docs/1.3/json/#dependencies) where the object has a property `dependsOn`.  In the implementation of the model, there is a list of `Dependencies` which seems to create a circular reference.

Is there a way to access the Depends on or is there an issue with the Model implementation?

**Comment by stevespringett** [comment]
Field names between XML and JSON along with structure are nearly identical. However, there are a few exceptions and the `dependsOn` is one of them. This is handled by custom (de)serializers by Jackson. We're also having to account for a legacy dependency extension so if you see some oddities in there with a namespace, its related to that.

https://github.com/CycloneDX/cyclonedx-core-java/blob/master/src/main/java/org/cyclonedx/util/DependencySerializer.java

**Comment by stevespringett** [comment]
To add dependencies to the Dependency object, simply call `addDependency()`. The (de)serialization will take care of everything for you.

Yes, circular dependencies are possible and are there by design. However, all official CycloneDX implementations only add direct dependencies, thus creating a graph.

**Comment by goneall** [comment]
@stevespringett Thanks for the quick response.

If I want to use the model to create a dependency graph, do I need to walk the entire tree watching out for cycles and create the dependency relationship between all `bomRef`s and the `bomRef`s in the dependencies?

**Comment by stevespringett** [comment]
I typically use the bomref as the key of a map, that way I don't create duplicate dependency objects for the same bomref.

When creating the graph, simply create a dependency object for every component, and if that component has direct dependencies, add them to the dependency object for that component.

**Comment by goneall** [comment]
I think I get it - just checking to make sure.

The `dependencies` is a collection of trees with possible cycles at the top level of the CycloneDX SBOM.  

Each dependency in the collection consists of a BomRef which can be used to locate a Component which has a the dependencies.  the `dependencies` property in the `Depencency` is also a collection of trees with possible cycles with the top level representing direct dependencies to the Component referred to by the BomRef.

Is this correct?

**Comment by stevespringett** [comment]
Correct. An example XML/JSON can be found here.
https://cyclonedx.org/use-cases/#dependency-graph

**Comment by goneall** [comment]
Got it - going to close this issue as resolved.

Thanks @stevespringett
