### ISSUE TITLE
Component model missing attribute name mapping for `mime-type`

### ISSUE THREAD

**Issue by dmeibusch** [CycloneDX/cyclonedx-core-java#171]
https://github.com/CycloneDX/cyclonedx-core-java/blob/f8060118e7ed063193a359c3fe445e9dc16526a0/src/main/java/org/cyclonedx/model/Component.java#L117

Jackson annotation should be:
```
    @JacksonXmlProperty(isAttribute = true, localName = "mime-type")
```

**Comment by stevespringett** [comment]
Thanks for reporting. This has been resolved in Core Java v6.0.0
