### ISSUE TITLE
org.cyclonedx.BomGenerator does not include children components

### ISSUE THREAD

**Issue by pierre-ernst** [CycloneDX/cyclonedx-core-java#2]
When generating the BOM with transitive dependencies

e.g.: application > library1 > library1.1

the <components> block of library1 does not include library1.1

Expected output:

<bom>
  <components>
    <component type="application">
      <name>myApplication</name>
      <components>
        <component type="library">
          <name>library1</name>
          <components>
            <component type="library">
               <name>library1.1</name>
            </component>
          </components>
        </component>
      </components>
    </component>
  </components>
</bom>

**Comment by stevespringett** [comment]
The core library doesn't handle transitive dependencies as it's ecosystem agnostic. It expects that the ecosystem specific resolution has already been done (via npm, nuget, pypi, maven, etc) and that it's being supplied all the dependencies. 

For Java, refer to the Maven plugin as it handles direct and transitive dependencies
