### ISSUE TITLE
Issue reading licenses in CycloneDX generated BOM

### ISSUE THREAD

**Issue by gtludwig** [CycloneDX/cyclonedx-core-java#222]
A work colleague created an application that generates a BOM using this library.

I have created a Spring Boot application where I need to read that BOM and do something. 

I am having issues reading the licenses nodes. 

The generation of the licenses node is as below:

```
"licenses": {
  "licenses": [
    {
      "id": "Apache 2.0"
    }
  ]
}, // ...
```

But the only way I can make it work is:
```
"licenses": [
  {
    "id": "Apache 2.0"
  }
], // ...
```

Is this an expected behavior?

**Comment by stevespringett** [comment]
That should not be happening. Can you provide the code that generated the first snippet?

The Maven and Gradle plugin, as well as Dependency-Track and NexusIQ all use this library and generate correct license nodes. So I'm wondering if we're hitting some corner case or not.

Also, what version of the library are you using?

**Comment by gtludwig** [comment]
Upon further investigation, we discovered an issue in my colleague's code.
