### ISSUE TITLE
Generate Java SBOM steps

### ISSUE THREAD

**Issue by VASAVI512** [CycloneDX/cyclonedx-core-java#229]
Hello,

Though this is very small thing for you, i could not find steps for generating java SBOM from this code. could not find the mail class as well.
Can you tell how to generate Java SBOM.

Regards,
Vasavi

**Comment by stevespringett** [comment]
This is a library for developers to programmatically interact with. Please reach out on Slack with questions.

**Comment by dstutz** [comment]
"generateBom" method from the maven plugin is a good start:

https://github.com/CycloneDX/cyclonedx-maven-plugin/blob/master/src/main/java/org/cyclonedx/maven/BaseCycloneDxMojo.java#L291
