### ISSUE TITLE
Should `cpe` be "un-deprecated"?

### ISSUE THREAD

**Issue by tsjensen** [CycloneDX/cyclonedx-core-java#233]
Currently, the `getCpe()` and `setCpe()` methods in `Component` are still [marked as deprecated](https://github.com/CycloneDX/cyclonedx-core-java/blob/2ee9002c7b8ceee9f161b6924918e9419584af38/src/main/java/org/cyclonedx/model/Component.java#L271-L287). However, in the spec, the deprecation status [was removed](https://github.com/CycloneDX/specification/issues/105).

Therefore, should we also remove the deprecation status of these methods in the Java API?

**Comment by stevespringett** [comment]
Good catch. Releasing an updated version soon

**Comment by tsjensen** [comment]
Great - thank you for the quick response!
