### ISSUE TITLE
Error in ExternalReferenceSerializer

### ISSUE THREAD

**Issue by jszgh** [CycloneDX/cyclonedx-core-java#237]
When writing an ExternalReference to xml or json, you check the url string by using "new URL(url).toURI()".
If this call throws an Exception the ExternalReference is skipped.
This is not correct. Java only accepts urls, for which it has a protocol handler. On every other url Java throws a MalformedURLException.
So you may have a correct url, but Java does not know the protocol and throws a exception.
Because of this test, ExternalReferences with valid urls are skipped.
So you should just write out the ExternalRefererence as it is.

**Comment by stevespringett** [comment]
Thanks for identifying the issue. I've corrected the issue and will be pushing out a new release shortly.
