### ISSUE TITLE
JAVA API

### ISSUE THREAD

**Issue by lyx1213** [CycloneDX/cyclonedx-core-java#25]
I have a java jar /zip project, I want to generate a BOM with Java API instead of maven plugin, what should I do?
![image](https://user-images.githubusercontent.com/40421870/72488163-1d177280-384b-11ea-9afd-39939331aa22.png)

**Comment by stevespringett** [comment]
The API is lower level, so you'll need to programmatically build up the BOM yourself with all the correct information. The Maven plugin, Gradle plugin, Dependency-Track, and OSS Toolkit are all consumers of the Java API. So for real world examples of how to use it, refer to the sources for each of those projects.

You can also read the Javadoc which is published to Maven Central, or simply look at the sources.

**Comment by lyx1213** [comment]
OK, Thanks!
