### ISSUE TITLE
BomGenerator does not include license text

### ISSUE THREAD

**Issue by florianrusch** [CycloneDX/cyclonedx-core-java#26]
I have the use case, that I need the license text in my `bom.xml` (see Bom 1.1 Schema).
Sadly it seems, that there is no logic, which buts it in the Document.

Thats the code which generates the license node:
https://github.com/CycloneDX/cyclonedx-core-java/blob/e0e8c8cae08844ccad57056cedf488925899c8d4/src/main/java/org/cyclonedx/AbstractBomGenerator.java#L81-L104

Is this a bug?

**Comment by stevespringett** [comment]
It looks like the code to add the license text is missing and needs to be added. Thanks for pointing that out.

**Comment by stevespringett** [comment]
Resolved in v2.6.0.

**Comment by florianrusch** [comment]
Wow, that was really fast! I had also started working on it yesterday to create a PR. But you were faster. Thanks for the fix!
