### ISSUE TITLE
BOMs do not validate anymore since the addition of license texts

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-core-java#28]
It seems that since the resolution of #26 calls to `bomParser.validate(bomFile)` fail with

    org.xml.sax.SAXParseException; systemId: file:/tmp/tmp1313740032155659095.tmp; lineNumber: 51; columnNumber: 70; cvc-attribute.3: The value 'UTF-8' of attribute 'encoding' on element 'text' is not valid with respect to its type, 'encoding'.

**Comment by stevespringett** [comment]
UTF-8 is not a valid value. The only supported value is `base64`. The encoding is optional. If specified, the only acceptable value (currently) is base64. Any other value should correctly fail to validate.

https://cyclonedx.org/docs/1.1/#type_encoding

**Comment by sschuberth** [comment]
Thanks for the clarification.
