### ISSUE TITLE
Support setting "undeclared elements" on License object

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-core-java#31]
The [spec](https://github.com/CycloneDX/specification/blob/fa07f76676df685d69cc93bf5a1e3ee238b0a0d3/schema/bom-1.1.xsd#L245-L251) seems to allow setting "undeclared elements" on `license` tags. It would be great if the [License API](https://github.com/CycloneDX/cyclonedx-core-java/blob/183324a9cbe5ff94ea4963fc69a211649a6d321c/src/main/java/org/cyclonedx/model/License.java#L24) would actually support that.

**Background:** We want to set additional meta-data on licenses, e.g. about whether it was a *declared* license or a *detected* license (also see [this discussion](https://github.com/heremaps/oss-review-toolkit/issues/2314#issuecomment-595101406)). If the Cyclone DX spec already allows to set additional elements in order to cover that use case, we just need API exposure of that feature. However, if the "undeclared elements" feature can not be used to cover this use-case, we probably need to think about extended both spec and API to allow e.g. a `type` attribute on the `license` tag as proposed in the linked post. Another possible name for a new attribute would be `origin`, so we could have something like `<license origin="meta-data">` (for *declared* licenses) and `<license origin="license-scanner">` (for *detected* licenses).

**Comment by stevespringett** [comment]
Elements in the CycloneDX spec can be extended one of two ways:

- The `<bom>`, `<component>` and `<externalReference>` elements can have arbitrary attributes added to them.
- Most other elements, including `<license>` can have arbitrary elements at the end of the node as long as those elements are in a different namespace.

So, something like this is certainly possible:
```xml
<license>
    <id>Apache-2.0</id>
    <name>Apache License 2.0</name>
    <ort:origin xmlns:ort="ort" value="license-scanner" />
</license>
```

It was always the plan to make these extension points accessible via the API, however, I haven't had the capacity to do it yet.

**Comment by stevespringett** [comment]
I have some working code (not yet checked in) that would essentially be implemented this way:

```java
License l = new License();
l.setId("Apache-2.0");
l.addExtensibleType(new ExtensibleType("ort", "origin", "license-scanner"));
```

This would produce the following fragment:
```xml
<license>
    <id>Apache-2.0</id>
    <origin xmlns="ort">license-scanner</origin>
</license>
```

Would this work?

**Comment by sschuberth** [comment]
For me that would work, yes, as long as it also validates via `bomParser.validate(bomFile)`.

At first I was slightly confused about the

    <origin xmlns="ort">license-scanner</origin>

that your code generates and the

    <ort:origin xmlns:ort="ort" value="license-scanner" />

that you were originally mentioning in your first post, but it looks like you've edited your first post to now also match the simpler syntax.

**Comment by CleanHit** [comment]
> ```java
> ```java
> 
> ```
> 
> 
> This would produce the following fragment:
> ```
> <license>
>     <id>Apache-2.0</id>
>     <origin xmlns="ort">license-scanner</origin>
> </license>
> ```
> 
> 
> Would this work?
> ```

@stevespringett is there any new progress on that suggestion?

**Comment by stevespringett** [comment]
v2.7.0 has been published to Maven Central.
