### ISSUE TITLE
A component's description is not escaped

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-core-java#38]
I just noticed that a component's description is not escaped before writing the XML. I'd assume this is something the library should do, as the caller in theory does not know to which format the data will be serialized, and thus can't know about the required escaping, if any.

This was originally reported at https://github.com/oss-review-toolkit/ort/issues/2814.

**Comment by stevespringett** [comment]
Ah, thank you. Ideally, description would appear inside a CDATA.

**Comment by sschuberth** [comment]
Right, I was considering to wrap the description in `CDATA` on our side at first, but then went for escaping as that makes comparing our results to the ones of your Gradle plugin easier. Anyway, also the wrapping in `CDATA` should be done by this library IMO.

**Comment by stevespringett** [comment]
Correct. And since the Maven, Gradle, and ORT all use this library, they would all have the same expected output one they've all been updated to a fixed release.

**Comment by stevespringett** [comment]
The Java version is a bit in-flux at the moment. It's being updated to support CycloneDX 1.2 (as well as v1.1) and will output both XML and JSON.

The NPM version has taken priority lately, but will jump back on the Java version as soon as possible.

**Comment by sschuberth** [comment]
Cool, thanks for the information!

**Comment by stevespringett** [comment]
v3.0.0 is now available and resolved this issue. Closing.
