### ISSUE TITLE
Support version 1.6 of the specification

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-core-java#392]
See https://github.com/CycloneDX/specification/releases/tag/1.6.

**Comment by stevespringett** [comment]
See #391

**Comment by sschuberth** [comment]
> See #391

The PR has been merged and is included in [release 9.0.0](https://github.com/CycloneDX/cyclonedx-core-java/releases/tag/cyclonedx-core-java-9.0.0).
