### ISSUE TITLE
Compatility issues with dependency-check - no release of cyclonedx-core-java since oct 23

### ISSUE THREAD

**Issue by boardbloke** [CycloneDX/cyclonedx-core-java#399]
I can see on master, in pom.xml that jackson-dataformat-xml 2.16.1, but the currently released version (8.0.3) uses v2.15.3.

When used in a Gradle build (via the Cyclone DXP Plugin) that causes incompatibility issues with other plugins - like the dependency-check OWASP plugin - which is already using jackson v 2.16.1

That is, the version of jackson selected by Gradle for a build that contains both cyclone and owasp plugins is 2.16.1 and that causes cylonedx to crash.

Can we have a release that reflects what is on master please?

Many Thanks!
Neilll

**Comment by nscuro** [comment]
Jackson was updated to 2.17.1 in the recent 9.x releases.
