### ISSUE TITLE
toXmlString() of BomXmlGenerator throws "NoSuchMethodError" in new version 9.0.4

### ISSUE THREAD

**Issue by afsahsyeda** [CycloneDX/cyclonedx-core-java#446]
On trying to convert an xmlbom of BomXmlGenerator class to string using toXmlString(), I am getting a "NoSuchMethodError" in version 9.0.4. **This issue was not present in a previous version** (was using 7.3.2).
The issue occurs in the ObjectWriter.java class while trying to call "createGenerator" for XmlFactory. Here is the relevant screenshot:
![image](https://github.com/CycloneDX/cyclonedx-core-java/assets/115608771/6d33bf3e-0a8e-4184-a32a-f78bb80198ff)

**Comment by sschuberth** [comment]
We're [using `toXmlString()` just fine](https://github.com/oss-review-toolkit/ort/pull/8882/files#diff-44c29999327f1d9ec9292af06d7f663c3e4b2bc52d9b93990029e70a9b8608b3R372), so I believe this is something related to our code.

**Comment by afsahsyeda** [comment]
@sschuberth We are calling the toXmlString() function as is. It works in the previous versions.
![image](https://github.com/user-attachments/assets/5f0745d3-845a-4ed1-b1c4-b9c718cc0ab2)

**Comment by sschuberth** [comment]
By "code" I actually meant your build system code, i.e. management of dependencies. I could imagine that there's e.g. a conflict of Jackson library versions on your end that could lead to this.

**Comment by afsahsyeda** [comment]
> By "code" I actually meant your build system code, i.e. management of dependencies. I could imagine that there's e.g. a conflict of Jackson library versions on your end that could lead to this.

It works now, thanks!
