### ISSUE TITLE
Invalid BOM generated when adding more than 1 tool, only for XML format

### ISSUE THREAD

**Issue by jgraglia** [CycloneDX/cyclonedx-core-java#492]
Hi,

I have a problem when writing a BOM with 2+ tools, only in XML format.
The xml  is wrote but it is not valid : a `<tools>` element appears for each `<tool>`

The generated file looks like
```xml
<bom version="1" xmlns="http://cyclonedx.org/schema/bom/1.5">
  <metadata>
    <timestamp>2024-09-01T08:41:47Z</timestamp>
    <tools>
      <tool>
        <vendor>corp A</vendor>
        <name>tool A</name>
        <version>1-A</version>
      </tool>
    </tools>
    <tools>   <!-- pb here -->
      <tool>
        <vendor>corp B</vendor>
        <name>tool B</name>
        <version>1-B</version>
      </tool>
    </tools>
    <tools>   <!-- pb here -->
      <tool>
        <vendor>corp C</vendor>
        <name>tool C</name>
        <version>1-C</version>
      </tool>
    </tools>
  </metadata>
</bom>
```

This problem does **not** appears when serializing as json.
I notice that the tools section is deprecated and that there are some jackson annotations ([ref](https://github.com/CycloneDX/cyclonedx-core-java/blob/73cce4b7d95e71939bb4bce116e0c44b52290d5f/src/main/java/org/cyclonedx/model/Metadata.java#L70)) to handle a transition from `metadata > tools` to `metadata > components|services`

The problem is present with versions 1.5 and 1.6

I have setup a minimal testcase to reproduce the problem : [https://github.com/netceler/cyclonedx-core-java/commit/458cbec42304255fec845758e87608442fc43546](https://github.com/netceler/cyclonedx-core-java/commit/458cbec42304255fec845758e87608442fc43546)

* `should_write_a_single_tool_in_xml_format`  is ok
* `should_write_many_tools_with_json_format` is also ok
* `testIssuesWhenSerializingMultiplesToolsInXmlFormat` fails

_I originally found the bug with version `9.0.5` but it is also active with `9.0.6-SNAPSHOT`_

**Comment by nscuro** [comment]
Fixed by #568
