### ISSUE TITLE
JSON Serialization results in invalid CycloneDX file

### ISSUE THREAD

**Issue by jrshaffe** [CycloneDX/cyclonedx-core-java#505]
Serialization to JSON results in an invalid CycloneDx file.  Steps to reproduce:

- Clone the Spring Pet Clinic -> https://github.com/spring-projects/spring-petclinic
- Generate the SBOM via the gradle plugin -> ` ./gradlew cyclonedxBom`  (This bom is valid)
- Using Jackson read in the generated SBOM into an `Bom.class` object
- Using Jackson write that Object out to a file
- Using the cyclonedxBom cli or [website](https://cyclonedx.github.io/cyclonedx-web-tool/validate) check the file generated from the step above and get the following:

```
Unable to validate against any JSON schemas.
BOM is not valid.
```

I believe the following 2 objects are serialized incorrectly:

1. Licenses
```

Get
...
      "licenses": {
        "licenses": [
          {
            "id": "Apache-2.0"
          }
        ]
      }
```

Should be

```
          "licenses": [
            {
              "license": {
                "id": "Apache-2.0"
              }
            }
          ],
```

Dependencies 

Get:

```
    {
      "ref": "pkg:maven/org.springframework.boot/spring-boot-starter-actuator@2.5.6?type=jar",
      "dependsOn": [
        {
          "ref": "pkg:maven/org.springframework.boot/spring-boot-starter@2.5.6?type=jar"
        },
        {
          "ref": "pkg:maven/org.springframework.boot/spring-boot-actuator-autoconfigure@2.5.6?type=jar"
        },
        {
          "ref": "pkg:maven/io.micrometer/micrometer-core@1.7.5?type=jar"
        }
      ]
    },
```

Should be:

```
{
          "ref": "pkg:maven/org.springframework.boot/spring-boot-starter-actuator@2.3.5.RELEASE?type=jar",
          "dependsOn": [
            "pkg:maven/org.springframework.boot/spring-boot-starter@2.3.5.RELEASE?type=jar",
            "pkg:maven/org.springframework.boot/spring-boot-actuator-autoconfigure@2.3.5.RELEASE?type=jar",
            "pkg:maven/io.micrometer/micrometer-core@1.5.6?type=jar"
          ]
        }
```

**Comment by nscuro** [comment]
> * Using Jackson read in the generated SBOM into an Bom.class object
> * Using Jackson write that Object out to a file

Are you saying you're bypassing [`BomParserFactory`](https://cyclonedx.github.io/cyclonedx-core-java/org/cyclonedx/parsers/BomParserFactory.html) and [`BomGeneratorFactory`](https://cyclonedx.github.io/cyclonedx-core-java/org/cyclonedx/generators/BomGeneratorFactory.html) and using Jackson directly instead? 

There are quite a few custom (de-)serializers involved that won't be registered if you use your own `ObjectMapper`: https://github.com/CycloneDX/cyclonedx-core-java/blob/ca5308ae9698bc10147b2e8706da0db919795db1/src/main/java/org/cyclonedx/generators/AbstractBomGenerator.java#L59

**Comment by jrshaffe** [comment]
Thanks!  I didn't realize that.
