### ISSUE TITLE
How to associate copyright holders with licenses?

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-core-java#58]
Sorry for this more question-type kind of issue, but I'm currently trying to understand how you would associate a particular copyright holder with a particular license in CycloneDX. The component model has distinct field for license and copyrights:

https://github.com/CycloneDX/cyclonedx-core-java/blob/71d55c685af72a622ed37443add8425ca005b574/src/main/java/org/cyclonedx/model/Component.java#L77-L78

So suppose a single component is licensed under both BSD and MIT, and the BSD licensed part has "Copyright bsd-guy" and the MIT licensed part has "Copyright MIT-guy". How would you properly reflect that in the data model as there's only a single copyright string?

**Comment by stevespringett** [comment]
At present, that functionality is not currently supported. The copyright statement at the component level is really designed to handle commercial software use cases (e.g. Copyright 2020 Acme Inc.). CycloneDX comes out of the software security world and does a very good job at those use cases, but does not handle some license/copyright use cases that well. This is one of them.

That said, the CycloneDX Core working group operates very differently than most standards - using a risk-based approach to standards development. We release an updated spec every year, usually around Q1/Q2. We are planning v1.3 of the spec. So this is an opportunity to jump in and improve the spec. I know you have a lot of experience with open source licenses and would value your input. If you have ideas for how this functionality could be achieved while still meeting the goals of the project, we'd love to hear them.

I created a [ticket](https://github.com/CycloneDX/specification/issues/43) to track the enhancement.

**Comment by sschuberth** [comment]
Thanks for the background information and the willingness to address this limitation. I'll close this issue then and comment over at the new specification issue if I have a proposal how to improve this scenario in CycloneDX.
