### ISSUE TITLE
BomParser.validate() should not fail for SPDX LicenseRefs

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-core-java#8]
I'm in the process of writing a CycloneDX BOM reporter for [ORT](https://github.com/heremaps/oss-review-toolkit) and I'm facing a validation issue for license ids that are SPDX LicenseRefs. If a license's `id` is something like "LicenseRef-scancode-mit-taylor-variant" I get:

```
Collection should be empty but contained [org.xml.sax.SAXParseException; systemId: file:/tmp/tmp7460662245339740355.tmp; lineNumber: 333; columnNumber: 68; cvc-enumeration-valid: Value 'LicenseRef-scancode-mit-taylor-variant' is not facet-valid with respect to enumeration '[0BSD, AAL, ADSL, ...]'
```

To me, the [spec](https://github.com/CycloneDX/specification/blob/fc6acef1ad75c36e7a41c3db165fe5fd0c5cd4eb/schema/bom-1.1.xsd#L223-L227) is a bit unclear whether this is intended behavior or not. I was assuming `id` could be either a "core" SPDX license id or a LicenseRef, and only if it is neither use `name` instead. However, it seems that `id` must only be "core" SPDX licnese ids, and anything else goes to `name`.

Could you please clarify on the intended behavior?

**Comment by stevespringett** [comment]
In CycloneDX, there are three potential elements for license, the ID (which is a core SPDX id), the license expression (which is an unvalidated but assumed to be accurate expression or complex SPDX id), or as a last resort, the license name.

**Comment by sschuberth** [comment]
Ok, so I'll prefer to set the `expression` in `LicenseChoice` if I have it, and otherwise create individual `License` entries in `LicenseChoice` which have *either* the `id` set (for valid core SPDX ids), *or* the name set (for anything else including SPDX LicenseRefs). Correct?

**Comment by stevespringett** [comment]
Thats correct
