### ISSUE TITLE
BOM JSON Parsing fails when license expression is used

### ISSUE THREAD

**Issue by cmbaatz** [CycloneDX/cyclonedx-core-java#80]
When a BOM uses a license expression instead of identifying individual licenses org.cyclonedx.util.LicenseDeserializer throws a JsonProcessingException which effectively stops the parsing of the BOM.

**NOTE:** This bug only effects JSON BOM's it appears that the XML Parser correctly handles the condition.

**How to reproduce**
Attempt to parse a BOM with a component where the license is defined with an expression.
```json
    {
      "type": "library",
      "bom-ref": "pkg:maven/org.glassfish.hk2/osgi-resource-locator@1.0.1?type=jar",
      "publisher": "GlassFish Community",
      "group": "org.glassfish.hk2",
      "name": "osgi-resource-locator",
      "version": "1.0.1",
      "licenses": [{"expression": "(CDDL-1.0 OR GPL-2.0-with-classpath-exception)"}]
    }
```
**Root Cause**
The LicenseDeserializer class is attempting to convert the licenses block into an array of License objects which it then stores into a new LicenseChoice object.  Since the given block doesn't match a license entity a JsonProcessingException is thrown.

**What should happen**
When LicenseDeserializer throws a JsonProcessingException attempt to read deserialize the value into a new LicenseChoice object.  If the JsonProcessingException occurred because the licenses section is similar to above it will deserialize into the LicenseChoice object.  If the block is malformed this attempt to deserialize will only cause a JsonProcessingException so current failure logic will still apply.

**Comment by stevespringett** [comment]
Closing as fixed
